# Generated by Django 4.2.14 on 2024-07-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_cart_category_product_cartitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contacto",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="tecnologias",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Proyecto",
        ),
        migrations.DeleteModel(
            name="Tecnologia",
        ),
    ]
